version: "3.9"
services:
  worker:
    build: .
    environment:
      STRING_SESSION: $STRING_SESSION
      STRING_SESSION2: $STRING_SESSION2
      STRING_SESSION3: $STRING_SESSION3
      STRING_SESSION4: $STRING_SESSION4
      STRING_SESSION5: $STRING_SESSION5
      API_ID: $API_ID
      API_HASH: $API_HASH
      MONGO_DB_URI: $MONGO_DB_URI
      LOG_GROUP_ID: $LOG_GROUP_ID
      BOT_TOKEN: $BOT_TOKEN
      MUSIC_BOT_NAME: $MUSIC_BOT_NAME
      OWNER_ID: $OWNER_ID
      AUTO_LEAVING_ASSISTANT: $AUTO_LEAVING_ASSISTANT
      DURATION_LIMIT: $DURATION_LIMIT



      

    
